from setuptools import setup

setup(
    name='openreview-expertise',
    version='2.0.19',
    description='OpenReview paper-reviewer affinity modeling',
    url='https://github.com/openreview/openreview-expertise',
    author='OpenReview',
    author_email='harold@openreview.net, carlos@openreview.net',
    license='MIT',
    packages=[
        'expertise'
    ],
    install_requires=[
        'setuptools>=75.6.0',
        'openreview-py>=1.50',
        'numpy<2.3,>=1.26',
        'scipy',
        'adapter-transformers',
        'pandas',
        'nltk',
        'gensim==4.3.3',
        'torch',
        'cloudpickle',
        'scikit-learn',
        'tqdm',
        'pytorch_pretrained_bert',
        'ipdb',
        'spacy==3.7.2',
        'en_core_web_sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz ',
        'python-Levenshtein',
        'sacremoses',
        'rank_bm25',
        'pytest==7.3.0',
        'overrides==3.1.0',
        'flask==2.2.5',
        'flask-cors==6.0.0',
        'cffi>=1.0.0',
        'celery==5.3.0',
        "kombu>=5.3.0,<6.0",
        'redis',
        'pytest-celery',
        'shortuuid',
        'redisai',
        'python-dotenv',
        'importlib-metadata==4.13.0',
        'werkzeug==3.0.6',
        'adapter-transformers',
        'google-cloud',
        'google-cloud-storage',
        'google-cloud-aiplatform',
        'bullmq==2.11.0'
    ],
    zip_safe=False
)